name: turjman_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.0
  get_it: ^9.2.1
  glass: ^2.0.0+2
  flutter_bloc: ^8.1.0
  path_provider: ^2.1.5
  hydrated_bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.7.0
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900

    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/images/appLogo.png"
  adaptive_icon_foreground: "assets/images/appIcon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/appLogo.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/images/appLogo.png"

flutter_intl:
  enabled: true
